Neos:
  Neos:
    modules:
      management:
        submodules:
          task:
            controller: \Sitegeist\Bitzer\Application\Controller\BitzerController
            label: 'Sitegeist.Bitzer:Main:module.Bitzer.label'
            description: 'Sitegeist.Bitzer:Main:module.Bitzer.description'
            icon: 'fas fa-clipboard-list'
            privilegeTarget: 'Sitegeist.Bitzer:Module.Bitzer'
    userInterface:
      translation:
        autoInclude:
          Sitegeist.Bitzer:
            - 'NodeTypes/*'
            - 'Main'
            - 'Module.Bitzer'
            - 'NeosUiPlugin'
